// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsdcshnoziyepyvdrxgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzZGNzaG5veml5ZXB5dmRyeGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODk5MjAsImV4cCI6MjA3MDQ2NTkyMH0.gWDTGYeWhnLx-EayfS4-dUBG2b2JHSXvrSE4w3IuSEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});